#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ..:/workspace
      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    #env_file: .env

    environment:
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_DB=myapp 

    links:
      - mongo

    ports:
      - 3000:3000

  mongo:
    image: mongo
    
    restart: unless-stopped

    volumes:
      - /data/db

    ports:
      - 27017:27017